openapi: 3.0.0
info:
  version: 0.0.1
  title: Pagopa Redirect
  description: >
    Collection of all api used for perform a transaction using redirect payment instrument.
    Api's are tagged as follow:
      * `b2b - PSP side` are implemented and exposed by PSP to expose api's  to p retrieve redirection URL and perform refund
      * `b2b - pagoPA side` are implemented and exposed by pagoPA to receive authorization outcome
  contact:
    name: pagoPA - Touchpoints team
tags:
  - name: b2b - PSP side
    description: Api's to initialize and refund a transaction
  - name: b2b - pagoPA side
    description: Api's to notify transaction outcome
servers:
  - url: https://${host}
externalDocs:
  url: https://docs.pagopa.it/sanp/prestatore-di-servizi-di-pagamento/modalita-di-integrazione/integrazione-per-strumento-di-pagamento-tramite-redirect
  description: SANP
paths:
  /redirections:
    post:
      externalDocs:
        url: https://docs.pagopa.it/sanp/prestatore-di-servizi-di-pagamento/modalita-di-integrazione/integrazione-per-strumento-di-pagamento-tramite-redirect#api-recupero-url
        description: Api recupero URL (SANP)
      tags:
        - b2b - PSP side
      operationId: RetrieveRedirectUrl
      summary: Retrieve redirect URL
      description: Retrieve redirect URL to be followed to perform transaction payment
      security:
        - PspApiKeyAuth: []
      requestBody:
        $ref: '#/components/requestBodies/RedirectUrlRequest'
      responses:
        '200':
          description: Redirect url response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedirectUrlResponse'
        '400':
          description: Formally invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
              example:
                status: 400
                detail: Bad reqeuest
                idTransaction: 3fa85f6457174562b3fc2c963f66afa6
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
              example:
                status: 401
                detail: Unauthorized
                idTransaction: 3fa85f6457174562b3fc2c963f66afa6
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
              example:
                status: 500
                detail: There was an error processing the request
                idTransaction: 3fa85f6457174562b3fc2c963f66afa6
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: |-
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
        status:
          $ref: '#/components/schemas/HttpStatusCode'
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
        instance:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
        idTransaction:
          $ref: '#/components/schemas/PagopaIdTransaction'
    HttpStatusCode:
      type: integer
      format: int32
      description: |-
        The HTTP status code generated by the origin server for this occurrence
        of the problem.
      minimum: 400
      maximum: 600
      exclusiveMaximum: true
      example: 400
    RedirectUrlRequest:
      type: object
      description: Redirect URL request
      properties:
        idTransaction:
          $ref: '#/components/schemas/PagopaIdTransaction'
        idPsp:
          description: PSP identifier
          type: string
        amount:
          $ref: '#/components/schemas/AmountEuroCents'
        urlBack:
          description: pagoPA platform URL where redirect users after payment transaction have been completed
          type: string
          format: uri
        description:
          description: Payment description
          type: string
        paymentMethod:
          description: Redirect payment method type
          type: string
          enum:
            - BANK_ACCOUNT
        paName:
          description: Name of the payment notice issuer
          type: string
          minLength: 1
          maxLength: 70
        idPaymentMethod:
          description: Unique id of the payment method chosen by the user
          type: string
          format: uuid
      required:
        - idTransaction
        - idPsp
        - amount
        - urlBack
        - description
        - paymentMethod
      example:
        idTransaction: 3fa85f6457174562b3fc2c963f66afa6
        idPsp: idPsp
        amount: 99999999
        urlBack: https://psp.site/payment
        description: payment description
        paymentMethod: BANK_ACCOUNT
        paName: paName
        idPaymentMethod: f40ccb17-3b0b-43d2-942a-2686eb121c6a
    RedirectUrlResponse:
      description: Redirect URL response
      type: object
      properties:
        url:
          description: URL where user has to be redirect to start payment
          type: string
          format: url
        idTransaction:
          $ref: '#/components/schemas/PagopaIdTransaction'
        idPSPTransaction:
          description: Unique identifier for the payment operation PSP side
          type: string
        amount:
          $ref: '#/components/schemas/AmountEuroCents'
        timeout:
          description: Max time that pagoPA systems have to await for an outcome callback call. Any request received after this timeout will be discarded and transaction treated as for a missing callback call
          type: integer
          format: int32
          minimum: 0
          maximum: 600000
      required:
        - url
        - idTransaction
        - idPSPTransaction
        - amount
    AmountEuroCents:
      description: Amount for payments, in euro cents
      type: integer
      format: int32
      minimum: 0
      maximum: 99999999
    PagopaIdTransaction:
      description: Uniquely identify a transaction
      type: string
      minLength: 32
      maxLength: 32
      example: 3fa85f6457174562b3fc2c963f66afa6
  requestBodies:
    RedirectUrlRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RedirectUrlRequest'
  securitySchemes:
    PspApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: PSP api key
