openapi: 3.0.0
info:
  version: 0.1.0
  title: Pagopa eCommerce payment transactions service
  description: This microservice that handles transactions' lifecycle and workflow.
paths:
  /transactions:
    post:
      operationId: newTransaction
      parameters:
        - in: header
          name: x-transaction-origin
          schema:
            type: string
            pattern: 'IO|CHECKOUT|CHECKOUT_CART'
          required: false
          description: Transaction origin (populated by APIM policy)
      summary: Make a new transaction
      requestBody:
        $ref: "#/components/requestBodies/NewTransactionRequest"
      responses:
        '200':
          description: New transaction successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewTransactionResponse'
  /transactions/{transactionId}:
    get:
      operationId: getTransactionInfo
      parameters:
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: Transaction ID
      summary: Get information about a specific transaction
      responses:
        200:
          description: Transaction data successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionInfo"
        400:
          description: Invalid transaction id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        404:
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /transactions/{transactionId}/auth-requests:
    summary: Request authorization for the transaction identified by payment token
    post:
      operationId: requestTransactionAuthorization
      parameters:
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: Transaction ID
        - in: header
          name: x-pgs-id
          schema:
            type: string
            pattern: 'XPAY|VPOS'
          required: false
          description: Pgs identifier (populated by APIM policy)
      requestBody:
        $ref: "#/components/requestBodies/RequestAuthorizationRequest"
      responses:
        200:
          description: Transaction authorization request successfully processed, redirecting client to authorization web page
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestAuthorizationResponse"
        400:
          description: Invalid transaction id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        404:
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        409:
          description: Transaction already processed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        504:
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
    patch:
      operationId: updateTransactionAuthorization
      parameters:
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: Transaction Id
      requestBody:
        $ref: "#/components/requestBodies/UpdateAuthorizationRequest"
      responses:
        200:
          description: Transaction authorization request successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionInfo"
        400:
          description: Invalid transaction id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        404:
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        502:
          description: Bad gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        504:
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /transactions/payment-context-codes/{paymentContextCode}/activation-results:
    summary: PaymentToken related to cdInfoWisp and attivaRPT
    post:
      operationId: transactionActivationResult
      parameters:
        - in: path
          name: paymentContextCode
          schema:
            type: string
          required: true
          description: Payment context code (codice contesto pagamento)
      requestBody:
        $ref: "#/components/requestBodies/ActivationResultRequest"
      responses:
        200:
          description: Activation result for the transaction successfully processed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivationResultResponse"
        400:
          description: Invalid payment context code
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        404:
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        409:
          description: Transaction already processed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        502:
          description: Bad gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        504:
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /transactions/{transactionId}/user-receipts:
    post:
      operationId: addUserReceipt
      parameters:
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: Transaction ID
      summary: Add receipt for user to specific transaction
      requestBody:
        $ref: "#/components/requestBodies/AddUserReceiptRequest"
      responses:
        200:
          description: Receipt successfully added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddUserReceiptResponse"
        400:
          description: Invalid transaction id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        404:
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        422:
          description: Unprocessable entity (most likely the transaction is in an invalid state)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
components:
  schemas:
    RptId:
      type: string
      pattern: '([a-zA-Z\d]{1,35})|(RF\d{2}[a-zA-Z\d]{1,21})'
    Iban:
      type: string
      pattern: '[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{1,30}'
    PaymentContextCode:
      description: Payment context code used for verifivaRPT/attivaRPT
      type: string
      minLength: 32
      maxLength: 32
    PaymentNoticeInfo:
      description: Informations about a single payment notice
      type: object
      properties:
        rptId:
          $ref: '#/components/schemas/RptId'
        paymentContextCode:
          $ref: '#/components/schemas/PaymentContextCode'
        amount:
          $ref: '#/components/schemas/AmountEuroCents'
      required:
        - rptId
        - amount
      example:
        rptId: string
        paymentContextCode: paymentContextCode
        amount: 100
    PaymentInfo:
      description: Informations about transaction payments
      type: object
      properties:
        paymentToken:
          type: string
        rptId:
          $ref: '#/components/schemas/RptId'
        reason:
          type: string
        amount:
          $ref: '#/components/schemas/AmountEuroCents'
      required:
        - rptId
        - amount
      example:
        rptId: "77777777777302012387654312384"
        paymentToken: "paymentToken1"
        reason: "reason1"
        amount: 100
    NewTransactionRequest:
      type: object
      description: Request body for creating a new transaction
      properties:
        paymentNotices:
          type: array
          items:
            $ref: '#/components/schemas/PaymentNoticeInfo'
          minItems: 1
          maxItems: 5
          example:
            -  rptId: "77777777777302012387654312384"
               paymentContextCode: paymentContextCode1
               amount: 100
            -  rptId: "77777777777302012387654312385"
               paymentContextCode: paymentContextCode2
               amount: 200
        email:
          type: string
      required:
        - paymentNotices
        - email
    NewTransactionResponse:
      type: object
      description: Transaction data returned when creating a new transaction
      properties:
        transactionId:
          type: string
        payments:
          type: array
          items:
            $ref: '#/components/schemas/PaymentInfo'
          minItems: 1
          maxItems: 5
          example:
            - rptId: "77777777777302012387654312384"
              paymentToken: "paymentToken1"
              reason: "reason1"
              amount: 100
            - rptId: "77777777777302012387654312385"
              paymentToken: "paymentToken2"
              reason: "reason2"
              amount: 100
        status:
          $ref: "#/components/schemas/TransactionStatus"
        amountTotal:
          $ref: "#/components/schemas/AmountEuroCents"
        feeTotal:
          $ref: "#/components/schemas/AmountEuroCents"
        origin:
          description: cart origin
          enum:
            - IO
            - CHECKOUT
            - CHECKOUT_CART
            - UNKNOWN
        authToken:
          type: string
      required:
        - transactionId
        - amountTotal
        - status
        - payments
    RequestAuthorizationRequest:
      type: object
      description: Request body for requesting an authorization for a transaction
      properties:
        amount:
          $ref: "#/components/schemas/AmountEuroCents"
        fee:
          $ref: "#/components/schemas/AmountEuroCents"
        paymentInstrumentId:
          type: string
          description: Payment instrument id
        pspId:
          type: string
          description: PSP id
        language:
          type: string
          enum: [IT, EN, FR, DE, SL]
          description: Requested language
        details:
          description: Additional payment authorization details. Must match the correct format for the chosen payment method.
          oneOf:
            - $ref: "#/components/schemas/PostePayAuthRequestDetails"
            - $ref: "#/components/schemas/CardAuthRequestDetails"
          discriminator:
            propertyName: detailType
            mapping:
              postepay: "#/components/schemas/PostePayAuthRequestDetails"
              card: "#/components/schemas/CardAuthRequestDetails"
      required:
        - amount
        - fee
        - paymentInstrumentId
        - pspId
        - language
        - details
    PostePayAuthRequestDetails:
      type: object
      description: Additional payment authorization details for the PostePay payment method
      properties:
        detailType:
          type: string
        accountEmail:
          type: string
          format: email
          description: PostePay account email
      required:
        - detailType
        - accountEmail
      example:
        detailType: "postepay"
        accountEmail: "user@example.com"
    CardAuthRequestDetails:
      type: object
      description: Additional payment authorization details for credit cards
      properties:
        detailType:
          type: string
        cvv:
          type: string
          description: Credit card CVV
          pattern: "^[0-9]{3,4}$"
        pan:
          type: string
          description: Credit card PAN
          pattern: "^[0-9]{14,16}$"
        expiryDate:
          type: string
          description: Credit card expiry date. The date format is `YYYYMM`
          pattern: '^\d{6}$'
        holderName:
          type: string
          description: The card holder name
      required:
        - detailType
        - cvv
        - pan
        - expiryDate
        - holderName
      example:
        detailType: "card"
        cvv: 000
        pan: 0123456789012345
        expiryDate: "209901"
        holderName: "Name Surname"
    RequestAuthorizationResponse:
      type: object
      description: Response body for requesting an authorization for a transaction
      properties:
        authorizationUrl:
          type: string
          format: url
          description: URL where to redirect clients to continue the authorization process
        authorizationRequestId:
          type: string
          description: Authorization request id
      required:
        - authorizationUrl
        - authorizationRequestId
      example:
        authorizationUrl: https://example.com
    UpdateAuthorizationRequest:
      type: object
      description: Request body for updating an authorization for a transaction
      properties:
        authorizationResult:
          $ref: '#/components/schemas/AuthorizationResult'
        timestampOperation:
          type: string
          format: date-time
          description: Payment timestamp
        authorizationCode:
          type: string
          description: Payment gateway-specific authorization code related to the transaction
      required:
        - authorizationResult
        - timestampOperation
        - authorizationCode
      example:
        authorizationResult: OK
        timestampOperation: 2022-02-11T13:00:00+01:00
    AddUserReceiptRequest:
      type: object
      description: Request body for adding a user receipt to a transaction
      properties:
        outcome:
          type: string
          description: Nodo outcome enum
          enum:
            - OK
            - KO
        paymentDate:
          type: string
          description: Timestamp of transaction verification/activation
          format: date-time
        payments:
          type: array
          description: Payments associated to this transaction
          items:
            type: object
            description: Payment
            properties:
              paymentToken:
                type: string
                description: Payment token associated to this payment
              description:
                type: string
                description: Payment description
              creditorReferenceId:
                type: string
                description: Creditor reference id
              fiscalCode:
                type: string
                description: Receiving body fiscal code
              companyName:
                type: string
                description: Receiving body public name
              officeName:
                type: string
                description: Receiving office name
              debtor:
                type: string
                description: Debtor's id
            required:
              - paymentToken
              - description
              - creditorReferenceId
              - fiscalCode
              - companyName
              - officeName
              - debtor
          minItems: 1
          maxItems: 5
      required:
        - outcome
        - paymentDate
        - payments
    ActivationResultRequest:
      type: object
      description: Request body for activation result
      properties:
        paymentToken:
          type: string
      required:
        - paymentToken
    ActivationResultResponse:
      type: object
      description: Response body for activation result
      properties:
        outcome:
          type: string
          enum:
            - OK
            - KO
      required:
        - outcome
    AddUserReceiptResponse:
      type: object
      description: Response body for adding user receipt
      properties:
        outcome:
          type: string
          description: Nodo outcome enum
          enum:
            - OK
            - KO
      required:
        - outcome
    TransactionInfo:
      description: Transaction data returned when querying for an existing transaction
      allOf:
        - $ref: "#/components/schemas/NewTransactionResponse"
        - type: object
          properties:
            status:
              $ref: "#/components/schemas/TransactionStatus"
          required:
            - status
    AmountEuroCents:
      description: Amount for payments, in euro cents
      type: integer
      minimum: 0
      maximum: 99999999
    AuthorizationResult:
      description: Authorization result
      type: string
      enum:
        - OK
        - KO
    Beneficiary:
      description: Beneficiary institution related to a payment
      type: object
      properties:
        beneficiaryId:
          type: string
          minLength: 1
          maxLength: 35
        denominazioneBeneficiario:
          type: string
          minLength: 1
          maxLength: 70
        codiceUnitOperBeneficiario:
          type: string
          minLength: 1
          maxLength: 35
        denomUnitOperBeneficiario:
          type: string
          minLength: 1
          maxLength: 70
        address:
          type: string
          minLength: 1
          maxLength: 70
        streetNumber:
          type: string
          minLength: 1
          maxLength: 16
        postalCode:
          type: string
          minLength: 1
          maxLength: 16
        city:
          type: string
          minLength: 1
          maxLength: 35
        province:
          type: string
          minLength: 1
          maxLength: 35
        country:
          type: string
          pattern: '[A-Z]{2}'
      required:
        - beneficiaryId
        - denominazioneBeneficiario
    PaymentInstallments:
      description: Payment installments (optional)
      type: array
      items:
        $ref: '#/components/schemas/Installment'
    Installment:
      description: Payment installment
      type: object
      properties:
        installment:
          type: string
          minLength: 1
          maxLength: 35
        data:
          $ref: '#/components/schemas/InstallmentDetails'
    InstallmentDetails:
      description: Amount and reason related to a payment installment
      type: object
      properties:
        reason:
          type: string
          minLength: 1
          maxLength: 25
        amount:
          $ref: '#/components/schemas/AmountEuroCents'
    TransactionStatus:
      type: string
      description: Possible statuses a transaction can be in
      enum:
        - ACTIVATION_REQUESTED
        - ACTIVATED
        - AUTHORIZATION_REQUESTED
        - AUTHORIZED
        - AUTHORIZATION_FAILED
        - CLOSED
        - CLOSURE_FAILED
        - CLOSURE_ERROR
        - NOTIFIED
        - NOTIFIED_FAILED
        - EXPIRED
        - REFUNDED
    ProblemJson:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: |-
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
        status:
          $ref: "#/components/schemas/HttpStatusCode"
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
        instance:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    HttpStatusCode:
      type: integer
      format: int32
      description: |-
        The HTTP status code generated by the origin server for this occurrence
        of the problem.
      minimum: 100
      maximum: 600
      exclusiveMaximum: true
      example: 200
  requestBodies:
    NewTransactionRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NewTransactionRequest"
    RequestAuthorizationRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RequestAuthorizationRequest"
    UpdateAuthorizationRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UpdateAuthorizationRequest"
    AddUserReceiptRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AddUserReceiptRequest"
    ActivationResultRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ActivationResultRequest"
    ActivationResultResponse:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ActivationResultResponse"